FROM debian:10

ENV APACHE_RUN_USER = www-data 
ENV APACHE_RUN_GROUP = www-data

RUN apt-get update && apt-get install -y \
    apache2 \
    php \
    php-mysql \
    wget

RUN wget -qO- https://wordpress.org/latest.tar.gz | tar xvz -C /var/www/html --strip 1

COPY config.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

EXPOSE 80

CMD ["apache2-foreground"]